/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    faq: Faq;
    'contact-submissions': ContactSubmission;
    works: Work;
    'ai-translation-logs': AiTranslationLog;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'ai-translation-logs': AiTranslationLogsSelect<false> | AiTranslationLogsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ja' | 'en') | ('ja' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    about: About;
    service: Service;
    'ai-translation-settings': AiTranslationSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    'ai-translation-settings': AiTranslationSettingsSelect<false> | AiTranslationSettingsSelect<true>;
  };
  locale: 'ja' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * 管理者: 全権限。編集者: コンテンツ編集のみ可能（ユーザー追加・削除や設定変更は不可）。サービス管理者: AI翻訳設定などサービス提供側の設定を扱う実装会社用ロール（付け外しはサービス管理者のみ可能）。
   */
  roles: ('admin' | 'editor' | 'serviceAdmin')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * JPEG / PNG / WebP / GIF / AVIF、1 ファイル 10MB まで
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * 半角小文字の英数字とハイフンのみ、100文字以内。URL に使います。
   */
  slug: string;
  publishedAt: string;
  category: 'info' | 'press' | 'event';
  thumbnail?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'service' | 'pricing' | 'other') | null;
  /**
   * 数値が小さい順に表示されます
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  companyName?: string | null;
  email: string;
  phone?: string | null;
  /**
   * 案件固有の選択肢がある場合、project 側で select フィールドに差し替えてから利用する
   */
  inquiryType?: string | null;
  message: string;
  status: 'new' | 'inProgress' | 'done';
  /**
   * 管理者への通知メールの配信状態。自動で記録される。失敗のままなら「通知を再送」で送り直す
   */
  notificationStatus?: ('pending' | 'sent' | 'failed' | 'skipped') | null;
  /**
   * 送信できなかった理由。メールアドレスは伏せた短い文言だけを記録する
   */
  notificationError?: string | null;
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  /**
   * 半角小文字の英数字とハイフンのみ、100文字以内。URL に使います。
   */
  slug: string;
  category: 'web' | 'product' | 'mobile' | 'frontend' | 'branding';
  publishedAt: string;
  thumbnail?: (number | null) | Media;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-translation-logs".
 */
export interface AiTranslationLog {
  id: number;
  targetKind: 'collection' | 'global';
  targetSlug: string;
  targetId?: string | null;
  targetTitle?: string | null;
  executedBy?: (number | null) | User;
  sourceLocale: string;
  targetLocale: string;
  model: string;
  status: 'pending' | 'succeeded' | 'failed' | 'rejected';
  characterCount?: number | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  estimatedCostUsd?: number | null;
  translatedFieldCount?: number | null;
  skippedFieldCount?: number | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  news?: {
    /**
     * Allow clients to find news.
     */
    find?: boolean | null;
    /**
     * Allow clients to create news.
     */
    create?: boolean | null;
    /**
     * Allow clients to update news.
     */
    update?: boolean | null;
  };
  faq?: {
    /**
     * Allow clients to find faq.
     */
    find?: boolean | null;
    /**
     * Allow clients to create faq.
     */
    create?: boolean | null;
    /**
     * Allow clients to update faq.
     */
    update?: boolean | null;
  };
  works?: {
    /**
     * Allow clients to find works.
     */
    find?: boolean | null;
    /**
     * Allow clients to create works.
     */
    create?: boolean | null;
    /**
     * Allow clients to update works.
     */
    update?: boolean | null;
  };
  siteSettings?: {
    /**
     * Allow clients to find site-settings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update site-settings global.
     */
    update?: boolean | null;
  };
  homePage?: {
    /**
     * Allow clients to find home-page global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update home-page global.
     */
    update?: boolean | null;
  };
  about?: {
    /**
     * Allow clients to find about global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update about global.
     */
    update?: boolean | null;
  };
  service?: {
    /**
     * Allow clients to find service global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update service global.
     */
    update?: boolean | null;
  };
  /**
   * この日時を過ぎるとMCP接続を拒否します。未設定の既存キーも安全のため拒否されます。
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'ai-translation-logs';
        value: number | AiTranslationLog;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  thumbnail?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  companyName?: T;
  email?: T;
  phone?: T;
  inquiryType?: T;
  message?: T;
  status?: T;
  notificationStatus?: T;
  notificationError?: T;
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  publishedAt?: T;
  thumbnail?: T;
  summary?: T;
  body?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-translation-logs_select".
 */
export interface AiTranslationLogsSelect<T extends boolean = true> {
  targetKind?: T;
  targetSlug?: T;
  targetId?: T;
  targetTitle?: T;
  executedBy?: T;
  sourceLocale?: T;
  targetLocale?: T;
  model?: T;
  status?: T;
  characterCount?: T;
  inputTokens?: T;
  outputTokens?: T;
  estimatedCostUsd?: T;
  translatedFieldCount?: T;
  skippedFieldCount?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  news?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  faq?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  works?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  siteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  homePage?:
    | T
    | {
        find?: T;
        update?: T;
      };
  about?:
    | T
    | {
        find?: T;
        update?: T;
      };
  service?:
    | T
    | {
        find?: T;
        update?: T;
      };
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  logo?: (number | null) | Media;
  footerText?: string | null;
  companyInfo?: {
    address?: string | null;
    tel?: string | null;
    fax?: string | null;
  };
  /**
   * 表示順で並べる。/about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
   */
  headerNav?:
    | {
        label: string;
        /**
         * /about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * /about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
   */
  footerNav?:
    | {
        label: string;
        /**
         * /about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * プライバシーポリシー、特定商取引法、サイトマップなど、フッター下部に出すリンク。/about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
   */
  policyLinks?:
    | {
        label: string;
        /**
         * /about のような内部パス、https:// から始まる URL、mailto:、tel: のみ指定できます
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * https:// から始まる絶対 URL のみ指定できます
   */
  social?: {
    twitter?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  analytics?: {
    gaTagId?: string | null;
    gtmId?: string | null;
  };
  /**
   * 問い合わせフォームのスパム対策用
   */
  turnstileSiteKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    enabled?: boolean | null;
    title: string;
    subtitle?: string | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  services?: {
    enabled?: boolean | null;
    heading?: string | null;
    subheading?: string | null;
    items?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  aboutPreview?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  featuredNews?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?: (number | News)[] | null;
  };
  cta?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  hero: {
    enabled?: boolean | null;
    title: string;
    subtitle?: string | null;
  };
  mission?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    values?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  companyProfile?: {
    enabled?: boolean | null;
    heading?: string | null;
    rows?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  members?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          name: string;
          position?: string | null;
          bio?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: number;
  hero: {
    enabled?: boolean | null;
    title: string;
    subtitle?: string | null;
  };
  services?: {
    enabled?: boolean | null;
    heading?: string | null;
    items?:
      | {
          icon?: string | null;
          title: string;
          description?: string | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    enabled?: boolean | null;
    heading?: string | null;
    steps?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    enabled?: boolean | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-translation-settings".
 */
export interface AiTranslationSetting {
  id: number;
  /**
   * 月額プランの停止時はオフにすると即座に翻訳機能が止まります。保存済みの翻訳文は残り、手動での多言語入力も引き続き使えます。
   */
  enabled?: boolean | null;
  /**
   * API キーは環境変数（ANTHROPIC_API_KEY / OPENAI_API_KEY）で設定します。管理画面からは設定できません。
   */
  model: 'anthropic/claude-haiku-4-5' | 'anthropic/claude-sonnet-5' | 'openai/gpt-4o-mini' | 'openai/gpt-4.1';
  /**
   * 上限に達すると AI API を呼び出す前に翻訳を停止します（日本時間の月初に集計をリセット）。
   */
  limits: {
    monthlyRunLimit: number;
    monthlyCharacterLimit: number;
    monthlyCostLimitUsd: number;
    perRunCharacterLimit: number;
    cooldownSeconds: number;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  footerText?: T;
  companyInfo?:
    | T
    | {
        address?: T;
        tel?: T;
        fax?: T;
      };
  headerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  policyLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  social?:
    | T
    | {
        twitter?: T;
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  analytics?:
    | T
    | {
        gaTagId?: T;
        gtmId?: T;
      };
  turnstileSiteKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  services?:
    | T
    | {
        enabled?: T;
        heading?: T;
        subheading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  aboutPreview?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        image?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  featuredNews?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?: T;
      };
  cta?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  mission?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        values?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  companyProfile?:
    | T
    | {
        enabled?: T;
        heading?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  members?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              name?: T;
              position?: T;
              bio?: T;
              image?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        title?: T;
        subtitle?: T;
      };
  services?:
    | T
    | {
        enabled?: T;
        heading?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  process?:
    | T
    | {
        enabled?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        enabled?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-translation-settings_select".
 */
export interface AiTranslationSettingsSelect<T extends boolean = true> {
  enabled?: T;
  model?: T;
  limits?:
    | T
    | {
        monthlyRunLimit?: T;
        monthlyCharacterLimit?: T;
        monthlyCostLimitUsd?: T;
        perRunCharacterLimit?: T;
        cooldownSeconds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}